### ISSUE TITLE
sphinx не стартует

### ISSUE THREAD

**Issue by aaa4xu** [Asethon/AniDocker#11]
В цикле падает со следующей ошибкой:
```
sphinx_1       | standard_init_linux.go:190: exec user process caused "no such file or directory"
```

**Comment by Asethon** [comment]
@aaa4xu, попробуй это: http://qaru.site/questions/16101442/standardinitlinuxgo190-exec-user-process-caused-no-such-file-or-directory-docker

**Comment by aaa4xu** [comment]
Проблема точно в Windows 10 (проверил под mac и ubuntu), но заменой переносов строк она не решилась - теперь он в цикле перезагрузок вообще без какого-либо вывода в лог.

UPD: Пока писал это сообщение sphinx поднялся. Значит, проблема все же в этом.
