### ISSUE TITLE
Запуск окружения

### ISSUE THREAD

**Issue by aaa4xu** [Asethon/AniDocker#2]
1. Смущает эта строчка:
https://github.com/Asethon/AniDocker/blob/e0bb835f09b3147336055ec651489e044023485f/start.sh#L3
Мне кажется, он слишком много себе позволяет. Стоит рассмотреть возможность использования `docker-compose stop`/`docker-compose down`.

2. Не у всех контейнеров указан restart policy, а у тех, что указан, используется `restart: always`, что, имхо, оверкилл для dev окружения. Предлагаю указать им всем `unless-stopped`, что бы окружение не запускалось после перезапуска ПК.

3. Возможно, стоит добавить флаг `--build` к `docker-compose up`. Это будет тратить некоторое время при запуске (с учетом кешей, несколько секунд), но позволит не задумываясь делать `git pull && start.sh`.

**Comment by Asethon** [comment]
Прислушаюсь к данному комментарию.
Честно говоря, впервые пишу сам файлы для докера. Обычно только мелкие правки делал.
