### ISSUE TITLE
Использование latest образов

### ISSUE THREAD

**Issue by aaa4xu** [Asethon/AniDocker#3]
https://github.com/Asethon/AniDocker/blob/e0bb835f09b3147336055ec651489e044023485f/docker-compose.yml#L8

Использование latest образов - отличный способ сломать окружение для новых пользователей после выхода новой мажорной версии одного из контейнеров. Следует закрепить хотя бы мажорную версию для тех образов, которые это поддерживают.

После этого, к `docker-compose up`, возможно, следует добавить добавить флаг `--pull` что бы обнаруживать в dev окружении проблемы с обновленными зависимостями.

**Comment by Asethon** [comment]
Так же перепишу завтра.
Спасибо за предложения.
