### ISSUE TITLE
anilibria.loc

### ISSUE THREAD

**Issue by aaa4xu** [Asethon/AniDocker#5]
По каким причинам было добавлено использование домена `anilibria.loc`? Добавление в `hosts` выглядит довольно проблематично, а вот преимуществ над использованием параметра nginx `default_server` я не увидел.

**Comment by Asethon** [comment]
> По каким причинам было добавлено использование домена `anilibria.loc`? Добавление в `hosts` выглядит довольно проблематично, а вот преимуществ над использованием параметра nginx `default_server` я не увидел.

Технических причин нет.
Привычка создавать локальные сервера доменного уровня .loc, для сравнения с боем.

**Comment by Asethon** [comment]
@aaa4xu , получилось запустить сайт?

**Comment by aaa4xu** [comment]
@Asethon нет, на данный момент у меня две проблемы:
1. Сайт отвечает `Invalid Host header`. Пока не разбирался в чем причина.
2. Не коннектится pma, сейчас разбираюсь с этим.

**Comment by Asethon** [comment]
@aaa4xu , запусти nginx и phpmyadmin отдельно и скинь логи:

`docker-compose up nginx`
`docker-compose up phpmyadmin`

**Comment by Asethon** [comment]
@aaa4xu, и ещё. Ошибки nginx должны падать в logs/error.log
Скинь, что он говорит

**Comment by aaa4xu** [comment]
pma не коннектится т.к. у меня бд не запускается. Ее лог:
```
mariadb_1      | 2019-02-22 15:30:34 0 [Note] mysqld (mysqld 10.3.12-MariaDB-1:10.3.12+maria~bionic) starting as process 1 ...
mariadb_1      | 2019-02-22 15:30:35 0 [Note] InnoDB: Using Linux native AIO
mariadb_1      | 2019-02-22 15:30:35 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1      | 2019-02-22 15:30:35 0 [Note] InnoDB: Uses event mutexes
mariadb_1      | 2019-02-22 15:30:35 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1      | 2019-02-22 15:30:35 0 [Note] InnoDB: Number of pools: 1
mariadb_1      | 2019-02-22 15:30:35 0 [Note] InnoDB: Using SSE2 crc32 instructions
mariadb_1      | 2019-02-22 15:30:35 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
mariadb_1      | 2019-02-22 15:30:35 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1      | 2019-02-22 15:30:35 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mariadb_1      | 2019-02-22 15:30:35 0 [ERROR] InnoDB: The Auto-extending innodb_system data file './ibdata1' is of a different size 0 pages than specified in the .cnf file: initial 768 pages, max 0 (relevant if non-zero) pages!
mariadb_1      | 2019-02-22 15:30:35 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
mariadb_1      | 2019-02-22 15:30:35 0 [Note] InnoDB: Starting shutdown...
mariadb_1      | 2019-02-22 15:30:35 0 [ERROR] Plugin 'InnoDB' init function returned error.
mariadb_1      | 2019-02-22 15:30:35 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
mariadb_1      | 2019-02-22 15:30:35 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1      | 2019-02-22 15:30:35 0 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
mariadb_1      | 2019-02-22 15:30:35 0 [ERROR] Unknown/unsupported storage engine: InnoDB
mariadb_1      | 2019-02-22 15:30:35 0 [ERROR] Aborting
mariadb_1      |
```

nginx везде логи пустые.
UPD: nginx это моя проблема, docker решил не говорить, что порт занят и там висит вообще левое приложение.

**Comment by aaa4xu** [comment]
В readme в написано, что приложение нужно искать на `http://anilibria.loc:8080`, а вешается он на 80 порт, отсюда и проблема.

**Comment by aaa4xu** [comment]
Проблему с БД нашел - https://github.com/docker-library/mariadb/issues/95 Сейчас оформлю пул реквест с поддержкой запуска под windows

**Comment by Asethon** [comment]
> Проблему с БД нашел - [docker-library/mariadb#95](https://github.com/docker-library/mariadb/issues/95) Сейчас оформлю пул реквест с поддержкой запуска под windows

ок, жду
